SPEED_OF_LIGHT_IN_OPTICAL_FIBER = 2 * 10**8
C = SPEED_OF_LIGHT_IN_OPTICAL_FIBER

SPEED_OF_LIGHT_IN_VACCUM = 3 * 10**8

ATTENUATION_LENGTH_IN_OPTICAL_FIBER = 22 * 10**3
L_ATT = ATTENUATION_LENGTH_IN_OPTICAL_FIBER

ETA_ATM_PI_HALF_780_NM = 0.8  # atmospheric loss pointing straight up for 780 nm laser light
AVERAGE_EARTH_RADIUS = 6371e3

EARTH_MASS = 5.972e24  # earth mass
GRAVITATIONAL_CONSTANT = 6.67408e-11  # gravitational constant
