SPEED_OF_LIGHT_IN_OPTICAL_FIBER = 2 * 10**8
C = SPEED_OF_LIGHT_IN_OPTICAL_FIBER

SPEED_OF_LIGHT_IN_VACCUM = 3 * 10**8

ATTENUATION_LENGTH_IN_OPTICAL_FIBER = 22 * 10**3
L_ATT = ATTENUATION_LENGTH_IN_OPTICAL_FIBER
